version: "3.9"

services:
  chat_app:
    build: .
    image: flask_chat_app
    container_name: chat_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
